blinklabs-io/dingo

chainsync/chainsync.go, mempool/mempool.go
Initial Prometheus metrics to match the Intersect Haskell cardano-node metrics.
- cardano_node_metrics_blockNum_int
- cardano_node_metrics_slotNum_int
- cardano_node_metrics_txsProcessedNum_int
- cardano_node_metrics_txsInMempool_int
- cardano_node_metrics_mempoolBytes_int
This tracks the current chain tip and any transactions in the node's mempool.
=> feat: initial metrics to match cardano-node

chainsync.go, internal/node/node.go, metrics.go
Log blocks as they pass through
```
{"time":"2024-05-21T12:38:17.335494548-04:00","level":"INFO","msg":"running: node version devel (commit 505b65a)"}
{"time":"2024-05-21T12:38:17.3356932-04:00","level":"INFO","msg":"listening for ouroboros node-to-node connections on :3001"}
{"time":"2024-05-21T12:38:17.335814615-04:00","level":"INFO","msg":"listening for prometheus metrics connections on :12798"}
{"time":"2024-05-21T12:38:17.619189658-04:00","level":"INFO","msg":"connected to node at preview-node.play.dev.cardano.org:3001"}
{"time":"2024-05-21T12:38:17.923596397-04:00","level":"INFO","msg":"rollback: slot: 49653463, hash: 5756c04c3fd07e9a25f395bfc9f6384a510c2ed69cab7b0b857ba6e4118f18b0"}
{"time":"2024-05-21T12:38:19.536800748-04:00","level":"INFO","msg":"chain extended, new tip: …
```
=> feat: log blocks

database/database.go
It logs errors and slow queries in its own format by default
=> chore: disable default GORM logging

chainsync.go, internal/node/node.go, state/state.go
=> feat: use recent chain points as intersect for chainsync client

internal/node/node.go
It's not configurable yet, and it generates error logs when it can't connect to the default local endpoint
=> chore: disable tracing

database/commit_timestamp.go, database/database.go, database/txn.go, state/models/block.go, state/models/utxo.go, state/state.go
This adds support for managing a transaction across both DB backends. It uses this new support for creating a shared transaction for "atomic" write operations and using it for all operations that update the DB.
Fixes #105
=> feat: use shared DB transaction for updates in ledger state

config.go, conn_manager/connection_manager.go, conn_manager/connection_manager_test.go, internal/node/node.go, node.go, topology/topology.go, topology/topology_test.go
This reduces binary size when using node as a library and helps maintain isolation of components
=> chore: move topology and conn manager to sub-packages

cmd/node/main.go, go.mod, go.sum
Configures Go's GOMAXPROCS using our slog logger to match logging.
```
{"time":"2024-09-30T16:57:13.60613697Z","level":"INFO","msg":"maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined"}
```
=> feat: uber automaxprocs

listener.go, outbound.go
Before:
```
{"time":"2024-10-02T15:50:16.999576505Z","level":"INFO","msg":"maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined"}
{"time":"2024-10-02T15:50:16.999798605Z","level":"INFO","msg":"running: node version devel (commit 1d03356)"}
{"time":"2024-10-02T15:50:17.000176618Z","level":"INFO","msg":"listening for ouroboros node-to-node connections on 0.0.0.0:3001"}
{"time":"2024-10-02T15:50:17.000244064Z","level":"INFO","msg":"listening for prometheus metrics connections on 0.0.0.0:12798"}
{"time":"2024-10-02T15:50:17.217174315Z","level":"INFO","msg":"connected ouroboros to backbone.cardano.iog.io:3001"}
{"time":"2024-10-02T15:50:17.474158604Z","level":"INFO","msg":"chain rolled back, new tip: ff8bd997a9c3be29f231a505200ce99fee78b2e5d51bd4cd4ae270a6abf5f8bb at slot 136317911"} …
```
=> feat: pass our logger to gouroboros

Dockerfile, config.go, internal/config/config.go, internal/node/node.go
This is the same as the `ghcr.io/blinklabs-io/cardano-node` image's `run-node` configuration.
=> fix: use CARDANO_DATABASE_PATH for persistent storage

internal/config/config.go, internal/node/node.go
This also turns it off by default
=> feat: make chain-sync tip intersect configurable

.dockerignore, Dockerfile
This makes mounting volumes work more consistently with cardano-node
=> chore: update default docker database path

chainsync/chainsync.go, node.go, state/metrics.go, state/state.go
This moves the block/slot number metrics from chainsync and adds new metrics for the current epoch, the relative slot number in the current epoch, and the chain density (placeholder)
Fixes #60
=> feat: ledger metrics

database/types.go, state/certs.go, state/models/pool_registration.go
Neither database/sql or sqlite in general can handle values larger than int64, so we use a string type to store them in the database
=> fix: use string for uint64 database fields

database/database.go
Switching to WAL, disabling sync on write, and increasing the cache size give a ~20% improvement in sync speed for the preview network
=> chore: tune sqlite connection params

internal/config/config.go, internal/node/node.go
Create the initial UNIX socket. This will need some improvements around the socket file handling, but is suitable to begin work on wiring up node-to-client protocols.
=> feat: unix socket for ouroboros node-to-client

connmanager/listener.go, internal/node/node.go
This migrates the listeners from the internal node entrypoint to the node framework, which enables re-use of the listening port as the outbound source port
=> refactor: move listener and enable port re-use

peergov/peergov.go
This commit also removes duplicate 'component' tags from various log lines in the peer governor
Fixes #293
=> fix: don't try to reconnect to inbound peer addresses

config.go, go.mod, go.sum, internal/config/config.go, internal/node/node.go, internal/utxorpc/query.go, internal/utxorpc/submit.go, internal/utxorpc/sync.go, internal/utxorpc/utxorpc.go, internal/utxorpc/watch.go, node.go, utxorpc/utxorpc.go
This copies over a hollowed out version of the cardano-node-api UTxO RPC implementation.
This sets the framework for the items in #43
=> feat: stub utxorpc

state/models/models.go, state/models/tip.go, state/state.go
This creates a new database table to track the current tip separately from the blocks recorded in the database
=> feat: track chain tip explicitly

state/models/block.go, state/state.go
This is the first step in allowing us to directly iterate blocks from the blob store without needing any additional metadata
=> refactor: add block metadata to blob store

chainsync.go
The limit of 50 increases the chainsync speed with public nodes. Going higher than this risks violating the protocol buffer limits and breaking the connection
=> chore: increase chainsync pipeline limit

utxorpc/submit.go
This prevents line wrapping at 132 columns in the github UI (or my terminal 😅)
=> chore: wrap lines at 132 for github

database/database.go, database/plugin/log.go, database/plugin/metadata/metadata.go, database/plugin/metadata/sqlite/database.go, database/plugin/option.go, database/plugin/plugin.go, database/plugin/register.go
This introduces the idea of database plugins and creates a `sqlite` metadata plugin. The plugin package is heavily inspired by Adder. This doesn't change the base database metadata interface from *gorm.DB so it's a drop-in replacement.
=> refactor(database): sqlite metadata plugin

database/types.go, database/types_test.go
We must use mixed pointer and non-pointer receivers for our custom database types to satisfy both the sql.Scanner and driver.Valuer interfaces. Tests have been added to ensure that our custom types are working as they are supposed to.
=> fix: use correct receivers for custom database types

state/models/block.go
Construct a reasonable seek key for reverse iteration to improve performance when fetching recent blocks
=> fix: improve key iteration for recent blocks

mempool/consumer.go, mempool/mempool.go, txsubmission.go
This switches from a lossy push-based model to a much simpler pull-based model. It removes a level of locking and prevents potential goroutine leaks.
=> refactor: rework mempool consumer

database/commit_timestamp.go, database/database.go, database/plugin/metadata/sqlite/commit_timestamp.go, database/plugin/metadata/sqlite/database.go, database/plugin/metadata/store.go, database/types_test.go
Create a `MetadataStore` interface with the following methods to decouple the `database` package from `gorm.DB` directly.
The MetadataStore interface matches the `gorm.DB` type for the following functions.
- AutoMigrate
- Begin
- Close (really DB.DB().Close())
- Create
- DB
- First
- Order
- Where
We have also created custom functions.
- GetCommitTimestamp
- SetCommitTimestamp
- Transaction
This fully removes gorm from the `database` package.
Closes #325
=> feat(database): metadata store interface

.github/workflows/go-test.yml, connmanager/unix.go
This works much better for cross-platform support, and it should still be unique within a single process
=> refactor: use only UNIX socket file descriptor for remote address

mempool/mempool.go
We re-run validation on all TXs in the mempool when the chain is updated. This serves to purge TXs based on spent UTxOs and TTL
=> feat: purge mempool based on chain events

database/database.go, database/plugin/blob/badger/database.go, database/plugin/blob/badger/logger.go, database/plugin/blob/badger/metrics.go
Create a `badger` blob plugin. This doesn't change the base database blob interface from *badger.DB so it's a drop-in replacement.
=> refactor(database): badger blob plugin

database/commit_timestamp.go, database/database.go, database/plugin/blob/badger/commit_timestamp.go, database/plugin/blob/badger/database.go, database/plugin/blob/badger/metrics.go, database/plugin/blob/blob.go, database/plugin/blob/store.go
Create a `BlobStore` interface with the following methods to decouple the `database` package from `badger.DB` directly.
The BlobStore interface matches `badger.DB` type for the following functions.
- Close
- NewTransaction
We have also created custom functions.
- GetCommitTimestamp
- SetCommitTimestamp
Closes #326
=> feat(database): blob store interface

blockfetch.go, chainsync.go, go.mod, go.sum, state/chainsync.go, state/state.go
This prevents random disconnects during bulk chainsync due to exceeding protocol buffer sizes
=> fix: prevent exceeding blockfetch batch size

state/chainsync.go, state/state.go
This prevents cases where cached chainsync headers can get overwritten when there are multiple pending blockfetch batches
=> fix: additional locking in chainsync/blockfetch

database/block.go, database/commit_timestamp.go, database/database.go, database/database_test.go, database/txn.go, database/utxo.go, state/state.go, state/view.go
Replace the Database interface with a Database struct and get rid of the entire InMemoryDatabase and PersistentDatabase separation.
=> refactor(database): collapse database interface into struct

database/certs.go, database/plugin/metadata/sqlite/certs.go, database/plugin/metadata/store.go, state/certs.go
Update `processTransactionCertificates` so it does not need to be aware of which database stores certificates. This requires creation of setters in `database` which calls the correct underlying store interface.
=> refactor(database): setters for pool and stake certificates

database/certs.go, database/plugin/metadata/sqlite/certs.go, database/plugin/metadata/store.go, state/view.go
Update `PoolRegistration` and `StakeRegistration` in ledger state view with new getters in the `database` package to return these certificates from the database.
=> refactor(database): getters for pool and stake registration certificates

database/database.go, database/txn.go
This allows metadata-only and blob-only DB transactions. It also restricts updating the commit timestamp to transactions that use both.
=> refactor: allow split database transactions

config/cardano/node.go
If the given paths to the genesis files in the cardano-node config are absolute, use them. Otherwise, prepend the `config.json` directory to the file names.
Closes #519
=> fix(config): support absolute paths in cardano-node config

database/epoch.go, database/tip.go, database/utxo.go, state/queries.go, state/state.go
Remove the funcs on database which executed the database type methods and switch to simply using those methods directly.
=> refactor(database): remove funcs and use database

state/chain.go
We watch for chain update events when starting a chain iterator to make sure that we don't miss a rollback event
=> refactor: chain iterator rollback event handling

database/block.go, state/chain.go, state/chainsync.go, state/state.go
* create "block index" for explicit chain ordering
* add BlockByIndex()
* remove unused BlockByNumber()
* modify BlocksRecent() to iterate block index keys
* track last point in chain iterator for rollback handling
Fixes #574
=> refactor: use block index for iterating chain

database/plugin/metadata/sqlite/models/auth_committee_hot.go, database/plugin/metadata/sqlite/models/deregistration.go, database/plugin/metadata/sqlite/models/deregistration_drep.go, database/plugin/metadata/sqlite/models/drep.go, database/plugin/metadata/sqlite/models/models.go, database/plugin/metadata/sqlite/models/registration.go, database/plugin/metadata/sqlite/models/registration_drep.go, database/plugin/metadata/sqlite/models/resign_committee_cold.go, database/plugin/metadata/sqlite/models/stake_registration_delegation.go, database/plugin/metadata/sqlite/models/stake_vote_delegation.go, database/plugin/metadata/sqlite/models/stake_vote_registration_delegation.go, database/plugin/metadata/sqlite/models/update_drep.go, database/plugin/metadata/sqlite/models/vote_delegation.go, database/plugin/metadata/sqlite/models/vote_registration_delegation.go
Initial metadata models so we can start tracking changes such as drep registrations, especially tracking the deposits.
=> feat(database): governance certificates models

chain/chain.go, chain/chain_test.go, chain/errors.go, chain/iter.go
This extends the chain support to allow adding a series of headers, querying their range, and replacing headers with blocks. This also adds various tests for chain support
Fixes #583
=> feat: support for block headers in Chain

chain/chain.go, chain/chain_test.go, chain/iter.go
=> refactor: make chain iterator updates synchronous

internal/node/node.go, node.go
=> feat: shutdown node cleanly on signal

cmd/dingo/load.go, cmd/dingo/main.go, cmd/dingo/serve.go, internal/config/config.go, internal/config/config_test.go, internal/node/load.go, internal/node/node.go
1. Added `--config` flag in cmd/dingo to make sure of custom configuration file as input.
2. Added proper yaml tags on all fields in the dingo `Config` struct to enable unmarshaling from YAML.
3. Implemented logic to load configuration from YAML first, and then override with environment variables
4. Updated node.Run() to accept loaded config from main instead of reloading internally.
5. Wrote unit tests to validate config loading with and without a YAML file.
6. Executed the cmd/dingo/main.go with and without config file as input and it is working fine.
Closes #529
=> feat(config): support dingo.yaml config file loading with env overrides in dingo

config/cardano/node.go, database/epoch.go, database/plugin/metadata/sqlite/epoch.go, database/plugin/metadata/store.go, ledger/chainsync.go, ledger/slot.go, ledger/slot_test.go, ledger/state.go
* add metadata DB endpoint for retrieving all epochs
* load and cache all epochs at startup and epoch rollover
* helper functions to load per-era genesis configs from reader for tests
Fixes https://github.com/blinklabs-io/dingo/issues/635
=> feat: slot calculation

ledger/state.go
This disables validation of "historical" (more than 2 weeks old) blocks and transactions by default
=> feat: configurable validation of historical blocks in ledger

database/plugin/metadata/sqlite/utxo.go, database/plugin/metadata/store.go, database/types/wrappers.go, database/utxo.go, ledger/certs.go, ledger/delta.go, ledger/state.go
Batch writes to the DB for produced UTxOs when not validating. This improves initial sync time by ~17%
=> refactor: use batch writes for UTxOs

README.md, dingo.yaml.example
1. Added dingo.yaml.example`with all config fields from the Config struct
2. Used default values from globalConfig.
3. Updated comments for each one in the config and updated the readme file as well to use this config file.
Closes #651
=> feat(config): Create dingo.yaml.example

internal/config/config.go
1. Added support in LoadConfig() to load configuration from ~/.dingo/dingo.yaml and /etc/dingo/dingo.yaml when no file is passed.
2. This function loads the built-in default if no configuration file is present.
Closes #622
=> feat(config): Configuration file loading should use a search path

database/account.go, database/plugin/metadata/sqlite/account.go, database/plugin/metadata/sqlite/drep.go, database/plugin/metadata/sqlite/models/drep.go, database/plugin/metadata/sqlite/models/pool.go, database/plugin/metadata/sqlite/pool.go
This also adds unique indexes on the pool/drep tables to allow the on-conflict clause to work
=> fix: use correct column in on-conflict clauses

ledger/chainsync.go, ledger/state.go
This prevents long pauses and reduces overall sync time. It also adds missing locks around the epoch rollover processing
Fixes https://github.com/blinklabs-io/dingo/issues/690
=> refactor: run cleanup of consumed UTxOs at epoch rollover

database/plugin/metadata/sqlite/utxo.go, database/plugin/metadata/store.go, database/utxo.go, ledger/state.go
This prevents long stop-the-world pauses in the ledger during cleanup of consumed UTxOs
Fixes #695
=> refactor: cleanup consumed UTxOs in batches

.github/workflows/publish.yml
Using a tarball everywhere makes installation using golang-npm possible.
=> ci(publish): use tarball for macos for now

ledger/chainsync.go, ledger/state.go
This allows it to work independently of the chainsync loop and prevents blocking
Fixes #706
=> refactor: make blockfetch timeout async

txsubmission.go
=> fix: don't send more than requested TxIds count

chain/chain_test.go, config.go, database/database.go, database/database_test.go, database/plugin/blob/badger/database.go, database/plugin/blob/store.go, dingo.yaml.example, internal/config/config.go, internal/config/config_test.go, internal/node/load.go, internal/node/node.go, node.go
1. Added badgerCacheSize to the config (dingo.yaml) to allow control over Badger's memory usage.
2. Ensured backward compatibility by providing a default badgerCacheSize fallback when the config is not set.
3. Added WithBadgerCacheSize and it sets the maximum cache size (in bytes).
4. Updated node.go and database initialization to pass the configured cache size.
5. Passed badger cache size through node.go to database and blob store layers.
6. Updated all unit test cases where database.New() was invoked.
Closes #694
=> feat(config): Make Badger cache size configurable

ledger/chainsync.go, ledger/metrics.go, ledger/state.go
=> feat: emit logs/metrics to track forks

config.go, dingo.yaml.example, internal/config/config.go, internal/config/config_test.go, internal/node/node.go, mempool/mempool.go, node.go
1. Added support for a configurable mempoolCapacity limit via dingo.yaml for enabling memory-based size restrictions on mempool transactions.
2. Updated AddTransaction() logic to enforce this limit and return an error if exceeded.
Closes #400
=> feat(mempool): Make mempool capacity configurable

cmd/dingo/main.go, config.go, dingo.yaml.example, internal/config/config.go, internal/config/config_test.go, internal/node/node.go, node.go, peergov/peergov.go
1. Added dev mode support via command line flags (--dev-mode), YAML config files (devMode: true) with proper precedence handling.
2. Modified peer governor to skip outbound connections when dev mode is enabled.
3. Updated test files to handle new dev mode parameter, added comprehensive test coverage, and updated dingo.yaml.example configuration files with proper documentation.
Closes #808
=> feat: Add dev mode in dingo

ledger/state.go, node.go
1. Added forgeBlock() method to LedgerState for creating empty blocks. 
2. Created an empty block with required header parameters such as (previous hash from current chain tip,incremented block number & slot number) and marshal blocks to CBOR & logged the hex string.
3. Schedule block forging at calculated block interval when dev mode is enabled.
4. Add devMode field to LedgerStateConfig and updated node configuration to pass dev mode to ledger state.
Closes #809
=> feat: Add initial block forge functionality

go.mod, go.sum, ledger/slot.go, ledger/state.go
When we don't have information about the current epoch, use the Shelley genesis slot length for calculating things like time-to-slot and the scheduler interval
=> fix: use Shelley genesis slot length at chain genesis

ledger/state.go
This prevents duplicate "chain extended" log messages. This also removes the possibility of the message triggering at chain genesis, so we are able to remove the special handling for it
=> fix: reset next batch when epoch rollover is needed

ledger/state.go, ledger/timer.go, ledger/timer_test.go
This adds a lock to each scheduler task to prevent concurrent runs. It also adds a mechanism for providing a notification when a task fails to run because the previous instance is still running
Fixes #824
=> refactor: prevent concurrent runs of same task in scheduler

config.go, dingo.yaml.example, internal/config/config.go, internal/config/config_test.go, internal/node/node.go, ledger/state.go, node.go
1.  Added ledgerValidateHistorical option to the dingo configuration, defaulting to '14d'.
2. This change replaces the hard-coded two-week historical validation threshold with a configurable setting.
Closes #672
=> feat: Make ledger historical validation threshold configurable

database/plugin/blob/gcs/database.go
Using gRPC provides a more compact data transfer and allows the client to use direct connectivity when running on Google Cloud. Disabling the client side metrics reduces the permissions required and prevents pushing telemetry to Google Cloud Monitoring.
=> feat(database): use grpc for gcs and disable telemetry

database/utxo.go
This reverts commit f33ada3bb6cf1ef1540aa6d8505a351d46d15882.
=> Revert "fix(database): keep consumed utxo metadata (#896)"
