blinklabs-io/dingo

- chainsync/chainsync.go
This also removes some unnecessary locking around chainsync clients which was causing problems.
> fix: update chain tip info

- node.go
- state/chain.go
- state/error.go
- state/event.go
- state/models/block.go
- state/state.go
* add read/write locking to ledger state
* chain iterator
* add blocks to ledger async via events
* helper functions for ledger state block model
* publish events on chain roll forward/back
* function to get current chain tip
> feat: ledger state improvements

- blockfetch.go
- chainsync.go
- chainsync/chainsync.go
- node.go
* use ledger for chain tracking
* publish chainsync roll forward/back events when acting as client
* switch to ledger chain iterator for chainsync server
> feat: integrate chainsync with ledger state

- state/state.go
> feat: handle rollback in ledger

- blockfetch.go
- chainsync.go
- config.go
- go.mod
- go.sum
- internal/node/node.go
- node.go
This also makes the initial chainsync intersect point(s) configurable
Fixes #88
> feat: use bulk chainsync for initial sync

- .github/workflows/go-test.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/publish.yml
- go.mod
- internal/node/node.go
The error log fix was required for the code to compile at all with Go 1.23
> chore: update to Go 1.22

- topology.go
- topology_test.go
These files are copied from here and slightly modified:
https://github.com/blinklabs-io/gouroboros/tree/84482014c20a92365323506df6d7b991857a9022
> feat: topology config file support

- connection_manager.go
- connection_manager_test.go
- go.mod
These files are copied from here and slightly modified:
https://github.com/blinklabs-io/gouroboros/tree/84482014c20a92365323506df6d7b991857a9022
> feat: connection manager

- state/state.go
This also uses the existing DB transaction instead of creating a new one
> fix: avoid deadlock when cleaning old UTxOs

- conn_manager/connection_manager.go
- topology/topology.go
- topology/topology_test.go
> feat: topology config bootstrap peer support

- connmanager/connection_manager.go
- internal/config/config.go
- internal/node/node.go
- node.go
Support a *slog.Logger in ConnectionManagerConfig and log new hosts being added at Debug level.
> feat: improve logging in connection manager for topology

- state/models/epoch.go
- state/models/models.go
- state/state.go
> feat: ledger epoch tracking

- state/models/block.go
- state/state.go
* add indexes to block table in database
* skip DB lookups for points past our current tip
> fix: optimize find chain intersect

- state/state.go
This avoids the possibility of deadlock when a consumer locks the ledger for reading and calls a query function that does its own read-locking
> fix: remove locking from ledger query functions

- go.mod
- go.sum
- node.go
- state/chain.go
- state/eras/allegra.go
- state/eras/alonzo.go
- state/eras/babbage.go
- state/eras/byron.go
- state/eras/conway.go
- state/eras/eras.go
- state/eras/mary.go
- state/eras/shelley.go
- state/models/era.go
- state/models/pparams.go
- state/state.go
- topology/topology.go
* split ledger config into separate type
* basic era tracking
* per-era functions for decoding and upgrading pparams
* persist active pparams in DB
> feat: protocol params tracking from genesis configs

- state/certs.go
- state/models/pool_registration.go
- state/models/pool_retirement.go
- state/models/stake_delegation.go
- state/models/stake_deregistration.go
- state/models/stake_registration.go
- state/state.go
> feat: track pool registrations and stake delegation

- chainsync/chainsync.go
- outbound.go
- peersharing.go
- state/chain.go
- state/eras/allegra.go
- state/eras/alonzo.go
- state/eras/babbage.go
- state/eras/conway.go
- state/eras/mary.go
- state/eras/shelley.go
- state/state.go
Also, updated formatting using `make format golines`.
> feat: sharable outbound peers

- state/chainsync.go
- state/state.go
* delay process of blocks in each blockfetch batch until batch is done
* write cached blocks in batches of 10
> feat: batch bulk block writes to database

- chainsync.go
This also removes a potential deadlock
> fix: remove unnecessary lock in chainsync

- event/event.go
This reduces lock contention in the event system by using a RWMutex and only write-locking when modifying the subscribers. It also makes the lock internal only to prevent unexpected deadlocks.
> refactor: event system locking

- state/chainsync.go
This will reclaim free space from the SQLite storage each epoch.
> feat: vacuum sqlite on epoch change

- node.go
Wire up handling for the chainsync protocol over node-to-client connections
> feat: chainsync over node-to-client

- state/chain.go
- state/state.go
> fix: support origin point for chainsync intersect

- localtxsubmission.go
- node.go
> feat: server-side support for local-tx-submission

- localtxmonitor.go
- mempool/mempool.go
- node.go
> feat: server-side support for local-tx-monitor

- go.mod
- go.sum
- localstatequery.go
- node.go
- state/queries.go
This implements server-side support for queries via the local-state-query protocol, including these queries:
* current era
* current protocol parameters
> feat: server-side support for local-state-query

- state/queries.go
This implements the following queries:
* SystemStart
* ChainPoint
* ChainBlockNo
* ShelleyEpochNo
> feat: support for system-start and chain tip related queries

- utxorpc/submit.go
> feat: utxorpc submit module

- utxorpc/sync.go
> feat: utxorpc sync module

- utxorpc/watch.go
> feat: utxorpc watch module

- state/state.go
- utxorpc/query.go
> feat: utxorpc query module

- peergov/peer.go
- peergov/peergov.go
> feat: track connection handshake params in peer governor

- go.mod
- go.sum
- state/chainsync.go
> feat: record genesis UTxOs in database

- go.mod
- go.sum
- state/chainsync.go
- state/eras/allegra.go
- state/eras/alonzo.go
- state/eras/babbage.go
- state/eras/conway.go
- state/eras/eras.go
- state/eras/mary.go
- state/eras/shelley.go
- state/models/block.go
- state/state.go
Calculate and track the rolling nonce (eta_v) for each block
> feat: track rolling nonce

- blockfetch.go
- chainsync/chainsync.go
- config.go
- config/cardano/node.go
- database/immutable/immutable_test.go
- internal/node/node.go
- localstatequery.go
- localtxmonitor.go
- mempool/mempool.go
- node.go
- peersharing.go
- state/chain.go
- state/metrics.go
- state/queries.go
- state/state.go
- tracing.go
- utxorpc/sync.go
Signed-off-by: Aurora Gaffney <aurora@blinklabs.io>
> chore: update TODO comments with issue numbers

- state/certs.go
- state/eras/allegra.go
- state/eras/alonzo.go
- state/eras/babbage.go
- state/eras/conway.go
- state/eras/eras.go
- state/eras/mary.go
- state/eras/shelley.go
- state/models/pool_registration.go
- state/models/stake_registration.go
- state/state.go
> feat: track deposit for certs

- go.mod
- go.sum
- state/chainsync.go
- state/eras/allegra.go
- state/eras/alonzo.go
- state/eras/babbage.go
- state/eras/conway.go
- state/eras/eras.go
- state/eras/mary.go
- state/eras/shelley.go
- state/view.go
Additionally:
* implement initial ledger view to satisfy validation rule interface
* generate CBOR for genesis UTxOs since none was provided
> feat: validate TXs

- internal/config/config.go
- internal/node/node.go
* allow disabling each listener
* add TCP node-to-client listener
> feat: make listeners more configurable

- state/state.go
* query consumed UTxOs once per cleanup
* reduce cleanup interval to 5 minutes
> refactor: improve consumed UTxO cleanup

- connmanager/listener.go
- connmanager/unix.go
> feat: provide unique remote address for UNIX connections

- localtxsubmission.go
- mempool/mempool.go
- node.go
- state/models/utxo.go
- state/state.go
- txsubmission.go
- utxorpc/submit.go
* update the mempool AddTransaction() function to take only type/bytes
* decode TX when adding to mempool
* validate TX when adding to mempool
* exclude deleted UTxOs when querying by ref
> feat: validate TXs on addition to mempool

- database/database_test.go
- database/plugin/metadata/sqlite/database.go
- database/plugin/metadata/store.go
- database/txn.go
> refactor(database): remove metadata store begin

- state/chain.go
This also adds an explicit signal that we've reached the current chain tip and prevents repeated rollbacks at chain origin
> refactor: use chain tip instead of ledger tip in chain iterator

- state/chainsync.go
This allows processing blocks in the ledger in contexts other than chainsync
> refactor: generalize block processing

- peergov/peergov.go
Since a host/port combination can be specified in the topology file more than once, create a precedence heiarchy to ensure there are no duplicates.
bootstrap peers < local root access points < public root access point
Closes #524
> fix(peergov): topology should have a precedence heiarchy

- database/plugin/metadata/sqlite/database.go
We're handling our own transactions.
> fix(database): disable default transaction in gorm

- state/chain.go
- state/chainsync.go
- state/state.go
* generalize raw chain tip lookup
* add chain iterator in ledger
* use blob-only DB txn when processing raw blocks
> refactor: process blocks async using chain iterator

- mempool/mempool.go
- state/chain.go
- state/chainsync.go
- state/event.go
> refactor: use single event queue for chain update to enforce ordering

- chain/chain.go
- chain/chain_test.go
- chain/iter.go
- event/event.go
- event/metrics.go
- state/state.go
This adds support to Chain for storing blocks in the database, memory, or a combination of both. This also updates EventBus to make the metrics optional
> feat: hybrid database/memory chain block storage

- state/state.go
We already delete the blocks in the Chain rollback
> fix: don't delete blocks in ledger rollback

- state/state.go
> fix: rework database recovery for async block processing

- chain/chain.go
- cmd/dingo/load.go
- cmd/dingo/main.go
- cmd/dingo/serve.go
- internal/node/load.go
- state/state.go
* expose Chain from LedgerState
* add convenience function for batch adding blocks to chain
* split CLI into subcommands
Fixes #598
> feat: support for loading from ImmutableDB

- database/plugin/metadata/sqlite/certs.go
- database/plugin/metadata/sqlite/models/account.go
- database/plugin/metadata/sqlite/models/models.go
Track stake credential registrations in an account table.
> feat(database): account tracking on credential registration

- database/certs.go
- database/plugin/metadata/sqlite/certs.go
- database/plugin/metadata/store.go
- ledger/certs.go
- ledger/eras/conway.go
> feat: track registration certificates and create account

- ledger/chainsync.go
- ledger/state.go
* move initial epoch creation to epoch rollover logic
* move era transition check before epoch rollover check
Fixes #636
> refactor: move genesis block processing out of chainsync loop

- ledger/state.go
This removes unnecessary DB updates within a single batch when processing blocks in the ledger
> refactor: update ledger tip in DB after each block batch

- .gitignore
- package-lock.json
- package.json
This was used to publish 0.6.0 with:
```
npm login
npm publish --access public
```
However, it still doesn't seem to work. Capturing the current state.
> build: attempt at golang-npm integration

- ledger/certs.go
- ledger/chainsync.go
- ledger/delta.go
- ledger/state.go
This adds a layer of abstraction which makes testing and future refactoring easier
> refactor: use LedgerDelta for processing/applying changes to the ledger

- ledger/chainsync.go
- ledger/state.go
* epoch start slot based on previous epoch end
* handle rollbacks outside of block batch
> refactor: process epoch rollover outside of block batch

- database/drep.go
- database/plugin/metadata/sqlite/drep.go
- database/plugin/metadata/sqlite/models/drep.go
- database/plugin/metadata/store.go
- ledger/certs.go
- ledger/delta.go
- ledger/eras/conway.go
- ledger/state.go
Create a drep entry for each registration and consume the deposit.
Closes #631
> feat: track drep registrations

- database/account.go
- database/plugin/metadata/sqlite/account.go
- database/plugin/metadata/sqlite/models/account.go
- database/plugin/metadata/sqlite/models/vote_registration_delegation.go
- database/plugin/metadata/store.go
- go.mod
- go.sum
- ledger/certs.go
- ledger/eras/conway.go
> feat: vote registration delegation certificate

- ledger/state.go
Perform block CBOR decoding async from block processing. This reduces initial sync time by approximately 15%
> refactor: async block decoding

- database/utxo.go
> fix: correct rollback logic for UTxOs

- ledger/delta.go
> fix: consider TX validity when processing

- internal/node/load.go
- ledger/state.go
- node.go
> refactor: move database init out of ledger

- database/database.go
- database/database_test.go
- database/plugin/blob/badger/database.go
- database/plugin/blob/badger/metrics.go
- database/plugin/blob/store.go
- database/plugin/metadata/sqlite/database.go
- database/plugin/metadata/store.go
- internal/node/load.go
- node.go
> refactor: make database metrics optional

- chainsync.go
> fix: handle reaching chain tip in chainsync consumer

- chainsync.go
> fix: handle rollback from chain iterator in chainsync server

- go.mod
- go.sum
- utxorpc/query.go
- utxorpc/submit.go
- utxorpc/sync.go
- utxorpc/watch.go
> chore(deps): update blinklabs-io/gouroboros to v0.127.0

- txsubmission.go
> refactor: don't log tx-submission error on shutdown

- ledger/chainsync.go
- ledger/state.go
1. Added a new field, checkpointWrittenForEpoch to the LedgerState to track whether a checkpoint has been saved for the current epoch and it ensures that only the first block processed in a new epoch is marked as a checkpoint.
2. Modified the block processing part to use the checkpointWrittenForEpoch flag. It correctly identifies and marks the first block of a new epoch as a checkpoint in the database.
3. Added an automatic cleanup process in the background after each epoch rollover to remove old block nonces data from database.
4. The cleanup logic preserves all block nonces from the last three epochs, as well as all nonces previously marked as checkpoints.
Closes #745
> feat: Cleanup old block nonce data

- Dockerfile
> feat(docker): add mithril-client

- cmd/dingo/main.go
- cmd/dingo/version.go
1. Added a new file cmd/version.go with a Cobra command implementation.
```
akhil-mac@Akhils-MacBook-Air dingo % ./dingo --version
dingo devel (commit 8cf773d)
akhil-mac@Akhils-MacBook-Air dingo %
```
Closes #913
> feat(cmd): Add a version cli command
